// Generated by CoffeeScript 1.3.3
(function() {
  var sourin;

  sourin = require('./sourin.coffee');

  module.exports = {
    convertObject: function(test) {
      var expect, obj, result;
      obj = {
        func: function() {
          return this;
        },
        number: 5,
        string: 'string',
        boolean: true,
        array: []
      };
      expect = '({func:function(){return this},number:5,string:"string","boolean":!0,array:[]})';
      result = sourin(obj, true);
      test.strictEqual(result, expect, 'Object convertion');
      return test.done();
    },
    convertArray: function(test) {
      var arr, expect, result;
      arr = [
        function() {
          return this;
        }, 5, 'string', true, {}
      ];
      expect = '[function(){return this},5,"string",!0,{}]';
      result = sourin(arr, true);
      test.strictEqual(result, expect, 'Array convertion');
      return test.done();
    }
  };

}).call(this);
